name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # important for force push

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # adjust if needed

      # 3️⃣ Get dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # 4️⃣ Build web release
      - name: Build Web
        run: flutter build web --release

      # 5️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true   # create gh-pages branch from scratch
          keep_files: false    # remove old files to avoid conflicts
